### ISSUE TITLE
作者可以为 Social-share.js 增加分享到微信的功能吗？

### ISSUE THREAD

**Issue by Kukmoon** [slince/social-share.js#1]
尊敬的作者，你好。

我博客用了 Social-share.js（[给 Hexo 博客的 Fluid 主题增加“分享到”模块](https://blog.kukmoon.com/c87ddd18.html)），体验很好。

但是它有个美中不足的地方是不能分享到微信。

我本来想凭借浅薄着前端知识自己搞，但是看到 `social-share.min.js` 和 `social-share.min.css` 密密麻麻没有换行的代码，我崩溃了。

在此请求作者为 Social-share.js 增加分享到微信的功能。

如果作者工作繁忙，没有时间，那能否麻烦作者简单指导我如何修改 `social-share.min.js` 和 `social-share.min.css`？我只需要把微信的图标以 SVG 格式嵌入 CSS，并在 JS 中调用 QRCODE.js 生成分享到微信所需的二维码。

**Comment by slince** [comment]
哈哈哈 有空我搞一搞

**Comment by Kukmoon** [comment]
好呀，等你更新。等你更新了 Social-share.js，我就换用新版本。

我因为急用，临时先弄了一个用着（看不懂你的JS源代码，只好在HTML里面修修补补）。我又不是学计算机的，对前端一窍不通，折腾死了。

![图片](https://user-images.githubusercontent.com/16938012/159975248-172233a0-b618-425d-8c52-bbb461346418.png)

![图片](https://user-images.githubusercontent.com/16938012/159975799-bee07be3-bd74-416e-bbbe-1171ba0b33e1.png)

**Comment by slince** [comment]
改过了 支持微信了

**Comment by Kukmoon** [comment]
哇，太棒了，谢谢！

**Comment by slince** [comment]
有一点不同 需要手动引一下 qrcode.js  readme上写了

**Comment by slince** [comment]
![image](https://user-images.githubusercontent.com/3785826/160148079-a686493c-cd69-4090-aba1-8a4902f7b8c5.png)

**Comment by Kukmoon** [comment]
谢谢作者大大！我又微调了一下二维码容器的大小，使用体验非常棒！如图所示

![图片](https://user-images.githubusercontent.com/16938012/161617989-49fa3ef8-45c0-45ab-9cef-f124615bdf31.png)-

- - -

另外我想问一下如何把微信图标放到第一位或者第二位呀？

**Comment by slince** [comment]
二维码容器大小默认是120 x 120 的，容器本身没有设置大小，设置了padding；如果调整了 二维码大小，容器也会跟着变；通过下面代码可以调整；也许是我wiki写的太简约了；

```javascript

{
    wechat: {
        width: 80
        height: 80
   }
}
```

支持的配置可以看源码  [https://github.com/slince/social-share.js/blob/master/src/provider.ts](https://github.com/slince/social-share.js/blob/master/src/provider.ts)  `GenericProvideConfig `

如果是改`padding` ` margin` 什么的 还是直接用样式覆盖吧
