### ISSUE TITLE
【Bug报告】图标字体翻车了

### ISSUE THREAD

**Issue by Kukmoon** [slince/social-share.js#2]
作者大大，您好。我用的是最新版本（[提交号：958b301](https://github.com/slince/social-share.js/commit/958b3018a2487695591a9ed61f6d06662d8e92e3)）。发现 Firefox 浏览器把图标字体显示成乱码，Chromium 内核的 Opera 和 Edge 浏览器显示方框。

P.S. 我是在本地测试的

![乱码](https://user-images.githubusercontent.com/16938012/160154848-4d85c617-267b-4cab-aa4e-acbea87bb323.png)

![我就调用了index.html下边的四个文件](https://user-images.githubusercontent.com/16938012/160154914-0b2666bc-46bf-4205-8e2c-40a5f1d698f5.png)

以下是测试案例的源代码：

```html
<html>
<head>	
	<link rel="stylesheet" type="text/css" href="./social-share.min.css">
</head>
<body>
	<div class="social-share-container">
	哈
	</div>
	<script src="./jquery.min.js"></script>
	<script src="./qrcode.min.js"></script>
	<script src="./social-share.min.js"></script>
	<script>
		new SocialShare('.social-share-container', {
			theme: 'circle'
		});
	</script>	
</body>
</html>
```

**Comment by slince** [comment]
修复了；其实也不算问题。在http服务下打开是没问题的 直接浏览器打开文件是不太行

**Comment by Kukmoon** [comment]
好哒，感谢大大~小长假快乐
