### ISSUE TITLE
建议修改 social-share-button 的 display:flex 属性以适应 Safari 浏览器

### ISSUE THREAD

**Issue by Kukmoon** [slince/social-share.js#3]
`social-share.min.css` 把样式 `.social-share-button` 的 `display` 属性设置为 `flex`。

![图片](https://user-images.githubusercontent.com/16938012/160166123-f04dc9c9-3378-4b72-b630-2299f78231d5.png)

为了保证 Safari 浏览器正常浏览，建议增补一条样式：`display:-webkit-flex` 并把它放在 `display:flex` 之前。

![图片](https://user-images.githubusercontent.com/16938012/160166693-67283cfc-9fcf-4cdb-986b-2f1fc94a940d.png)

**Comment by slince** [comment]
可以了
