### ISSUE TITLE
【求助】请问如何把微信图标放在第一位或者第二位呀？

### ISSUE THREAD

**Issue by Kukmoon** [slince/social-share.js#4]
作者大大你好哟~最新版的 social-share.js 我已经用上了，效果超棒的，好想给你点一万个赞！

![图片](https://user-images.githubusercontent.com/16938012/161619304-cdadc30e-44bd-4c9a-8721-0626fcaadcd7.png)

不过我有一点不习惯，微信放在最后一个。

请问怎么才能把微信放在第一个或者第二个呀？

P.S. 我试着改了源代码然后用 tsc 重新编译，结果失败了……

**Comment by slince** [comment]
有一个字段叫 sort 调小点

```javascript

{
   wechat: {
       sort: 1
  }
}

```

**Comment by Kukmoon** [comment]
作者大大要是方便的话可以顺便帮我编译一份吗？我已经把TypeScript的环境都删了……

**Comment by slince** [comment]
不用重新编译，现在就已经支持了

```javascript
new SocialShare('.social-share-container', {
    // 单独定义wechat分享参数,其它的同
    wechat: {
        sort: 1, // 排序参数，数字较小的展示在前面,默认999
        width: 120,
        height:120
    }
});
```

**Comment by Kukmoon** [comment]
太好了，谢谢作者大大！mua~

**Comment by Kukmoon** [comment]
感谢作者大大，我把它用在我博客上了。还写了篇文章介绍 Social-share.js 。详见：http://blog.kukmoon.com/c87ddd18.html

另外报个小bug：width和height这两个参数无法修改二维码所在的<div>的尺寸，我是自己修改CSS实现的。

修改前：

![修改前](https://user-images.githubusercontent.com/16938012/162460890-26a55dd2-9c07-4d10-b159-4d5a87c9a9bc.png)

修改了这里：

![修改了这里](https://user-images.githubusercontent.com/16938012/162461889-1ec3db1a-cff8-4ef1-a12c-2195650ce406.png)

修改后：

![修改后](https://user-images.githubusercontent.com/16938012/162462470-2ddb41a9-2e33-4d02-98ca-bfc76d66047d.png)
